# Generated by Django 4.0.1 on 2023-01-09 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to=settings.AUTH_USER_MODEL)),
                ('favorite', models.ManyToManyField(related_name='saved_favorites', to='estate.Favorite')),
            ],
        ),
    ]
