# Generated by Django 4.0.1 on 2023-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_compilation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='favorite',
            field=models.ManyToManyField(related_name='saved_favorites', to='estate.Annoucement'),
        ),
    ]
