# Generated by Django 4.0.1 on 2023-01-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_compilation_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='ceilings',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='annoucement',
            name='district',
            field=models.CharField(default='Центральный', max_length=40),
        ),
    ]
