# Generated by Django 4.0.1 on 2023-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='field_name',
            field=models.TimeField(auto_now=True),
        ),
    ]
