# Generated by Django 4.0.1 on 2023-01-28 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_message_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='field_name',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 7, 43, 37, 153260, tzinfo=utc)),
        ),
    ]
