# Generated by Django 4.0.1 on 2023-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='main_image',
            field=models.ImageField(blank=True, default='back1.png', upload_to='announcement_images/'),
        ),
    ]
